// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7nVpV5281amCxG8-2wjQ6w3ZSedz9QMc',
    appId: '1:269332936479:web:36911742569cd794d3222a',
    messagingSenderId: '269332936479',
    projectId: 'messageapp-dbdbc',
    authDomain: 'messageapp-dbdbc.firebaseapp.com',
    databaseURL: 'https://messageapp-dbdbc-default-rtdb.firebaseio.com',
    storageBucket: 'messageapp-dbdbc.appspot.com',
    measurementId: 'G-LVP7NE43SP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9P-_usWFgnNuNi4VRBRi0UhUZblse0KY',
    appId: '1:269332936479:android:3ce5538d12b5538ad3222a',
    messagingSenderId: '269332936479',
    projectId: 'messageapp-dbdbc',
    databaseURL: 'https://messageapp-dbdbc-default-rtdb.firebaseio.com',
    storageBucket: 'messageapp-dbdbc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXc78eSrtREkvywwWb7ST64YBKxVVvVMk',
    appId: '1:269332936479:ios:b531b25fcb187a04d3222a',
    messagingSenderId: '269332936479',
    projectId: 'messageapp-dbdbc',
    databaseURL: 'https://messageapp-dbdbc-default-rtdb.firebaseio.com',
    storageBucket: 'messageapp-dbdbc.appspot.com',
    iosBundleId: 'com.example.flutterPp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXc78eSrtREkvywwWb7ST64YBKxVVvVMk',
    appId: '1:269332936479:ios:da44c2d734281949d3222a',
    messagingSenderId: '269332936479',
    projectId: 'messageapp-dbdbc',
    databaseURL: 'https://messageapp-dbdbc-default-rtdb.firebaseio.com',
    storageBucket: 'messageapp-dbdbc.appspot.com',
    iosBundleId: 'com.example.flutterPp.RunnerTests',
  );
}
